#spring.application.name=devops2
#server.port=8080
#spring.jpa.hibernate.ddl-auto=create
#spring.config.import=secret.properties
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
##spring.datasource.url=${DATABASE_URL: jdbc:postgresql://localhost:5432}/devOpsW
#spring.datasource.url=${DATABASE_URL: }
#spring.datasource.username=${DATABASE_USERNAME:postgres}
#spring.datasource.password=${DATABASE_PASSWORD:}


spring.application.name=devops2
server.port=8080
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.netflix.service.discovery={SERVICE_DISCOVERY}


spring.datasource.netflix.service.discovery={EUREKA_SERVICE_DISCOVERY}
